# Arm the alarm automatically at your bed time (10pm in the example below) if:
# (1) the alarm was not already armed, and 
# (2) the family is home
#
# Send mobile notifications with tag "intrusion-auto-arm-disarm" - thus overwriting previous notifications
# of the same event type. This avoid HA notification accumulation in the mobile app.

alias: 'Intrusion: auto-arm at 10pm if we are home'
description: ''
trigger:
  - platform: time
    at: '22:00:00'
condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: disarmed
action:
  - service: alarm_control_panel.alarm_arm_home
    data: {}
    entity_id: alarm_control_panel.home_alarm
  - service: notify.notify
    data:
      title: Home Alarm now ARMED/HOME
      message: >-
        The alarm arms automatically in home mode at 10:pm when the family is
        home.
      data:
        tag: intrusion-auto-arm-disarm
  - service: script.sonos_say
    data:
      sonos_entity: media_player.kitchen
      volume: 0.4
      message: The alarm is now armed
      delay: '00:00:05'
mode: single
