alias: 'Intrusion: suggest arming (away) if nobody home in the evening'
description: 'Notify users suggesting them to arm the alarm in away mode if no member of the family is home in the evening'
trigger:
  - platform: time
    at: '23:00:00'
condition:
  - condition: state
    entity_id: group.family
    state: not_home
  - condition: state
    entity_id: alarm_control_panel.home_alarm
    state: disarmed
action:
  - service: notify.mobile_app_SAMPLE_ANDROID_PHONE
    data:
      message: It is late and nobody is home. Arm the system?
      data:
        tag: intrusion-suggest-arm
        url: /lovelace/security
        actions:
          - action: ARM_AWAY
            title: Arm away
          - action: DO_NOTHING
            title: Do nothing
      title: Consider arming the intrusion alarm
  - service: notify.mobile_app_SAMPLE_IPHONE
    data:
      message: >-
        It is late and nobody is home. Arm the system? Long press to see
        options.
      data:
        tag: intrusion-suggest-arm
        url: /lovelace/security
        actions:
          - action: ARM_AWAY
            title: Arm away
            destructive: true
          - action: DO_NOTHING
            title: Hide this notification
      title: Consider arming the intrusion alarm
mode: single
